### ISSUE TITLE
Review legacy asibot-main/share/userPrograms

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/asibot-hmi#4]
Review legacy `asibot-main/share/userPrograms`, maybe something reusable: [permalink](https://github.com/roboticslab-uc3m/asibot-main/tree/fcfa28e5a4e4fb05b1dcb62e709ac05f91aa45c0/share/userPrograms).

**Comment by PeterBowman** [comment]
I don't really think we can get much of the old Python scripts for ASIBOT. Most relevant stuff was [here](https://github.com/roboticslab-uc3m/asibot-main/blob/fcfa28e5a4e4fb05b1dcb62e709ac05f91aa45c0/share/userPrograms/asibot/functions.py), featuring a PortReader. This has been already implemented elsewhere (check [speechRecognition.py](https://github.com/roboticslab-uc3m/speech/blob/b8cdb2790250dcf43f38d162798556801fa4ea87/programs/speechRecognition/speechRecognition.py)), and remaining code is very ASIBOT-specific (5 axes).
